language: python
python:
  - "2.7"
  - "3.0"
  - "3.4"
sudo: true

before_install: "sudo apt-get install python-dev libevent-dev"

# command to install dependencies
install: pip install nose gevent; python setup.py install

# command to run tests
script: nosetests
